name: fintech
description: "A UAE phone top-up management application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  auto_route: ^9.3.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  intl: ^0.20.2
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  connectivity_plus: ^6.1.4
  drift: ^2.26.1
  drift_flutter: ^0.2.4
  toastification: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.25.2
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.4.1
  auto_route_generator: ^9.0.0
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true 