name: fintech
description: "A UAE phone top-up management application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  injectable: ^2.3.2
  auto_route: ^7.8.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  intl: ^0.19.0
  dio: ^5.5.0
  flutter_secure_storage: ^9.0.0
  flutter_screenutil: ^5.9.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true 