/*
// Mocks generated by Mockito 5.4.5 from annotations
// in fintech/test/features/top_up/data/repositories/top_up_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:fintech/features/top_up/data/datasources/top_up_data_source.dart'
    as _i2;
import 'package:fintech/features/top_up/data/entities/top_up_option_entity.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

/// A class which mocks [TopUpDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopUpDataSource extends _i1.Mock implements _i2.TopUpDataSource {
  MockTopUpDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.TopUpOptionEntity>> getTopUpOptions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopUpOptions,
          [],
        ),
        returnValue: _i3.Future<List<_i4.TopUpOptionEntity>>.value(
            <_i4.TopUpOptionEntity>[]),
      ) as _i3.Future<List<_i4.TopUpOptionEntity>>);

  @override
  _i3.Future<void> executeTopUp({
    required String? beneficiaryId,
    required int? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeTopUp,
          [],
          {
            #beneficiaryId: beneficiaryId,
            #amount: amount,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
*/
